# Generated by Django 5.1.15 on 2026-06-19 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenador',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrenador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contrato',
            name='entrenador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='academy.entrenador'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jugadores', to='academy.division'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='entrenador_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cluster', to='academy.entrenador'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='academy.jugador'),
        ),
        migrations.AddField(
            model_name='rencilla',
            name='jugador_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rencillas_a', to='academy.jugador'),
        ),
        migrations.AddField(
            model_name='rencilla',
            name='jugador_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rencillas_b', to='academy.jugador'),
        ),
        migrations.AddField(
            model_name='pista',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pistas', to='academy.sede'),
        ),
        migrations.AlterUniqueTogether(
            name='contrato',
            unique_together={('jugador', 'entrenador')},
        ),
        migrations.AlterUniqueTogether(
            name='rencilla',
            unique_together={('jugador_a', 'jugador_b')},
        ),
        migrations.AlterUniqueTogether(
            name='pista',
            unique_together={('sede', 'numero')},
        ),
    ]
