# Generated by Django 5.1.15 on 2026-06-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenador',
            name='foto_url',
            field=models.URLField(blank=True),
        ),
    ]
