# Generated by Django 5.1.15 on 2026-08-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_entrenador_foto_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenador',
            name='gestiona_todos_jugadores',
            field=models.BooleanField(default=False, help_text='Acceso a declarar ausencias de todos los jugadores.'),
        ),
        migrations.AddField(
            model_name='entrenador',
            name='jugadores_gestionados',
            field=models.ManyToManyField(blank=True, related_name='entrenadores_gestores', to='academy.jugador'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='categoria',
            field=models.CharField(blank=True, choices=[('ALTO_RENDIMIENTO', 'Alto rendimiento'), ('PROFESIONAL', 'Profesional nacional')], max_length=20),
        ),
        migrations.AddField(
            model_name='jugador',
            name='codigo_cliente',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='jugador',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='jugador',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jugador',
            name='telefono',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
