# Generated by Django 5.1.15 on 2026-08-05 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_entrenador_gestiona_todos_jugadores_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='densidad_max',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=120)),
                ('prioridad', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='MEDIA', max_length=6)),
                ('titulo', models.CharField(blank=True, max_length=160)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('NUEVO', 'Nuevo'), ('EN_PROGRESO', 'En progreso'), ('HECHO', 'Hecho'), ('DESCARTADO', 'Descartado')], default='NUEVO', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback / petición',
                'verbose_name_plural': 'Feedback y peticiones',
                'ordering': ['-created_at'],
            },
        ),
    ]
