# Generated by Django 5.1.15 on 2026-08-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_sedes_densidad_max_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='pista',
            name='superficie',
            field=models.CharField(choices=[('TIERRA', 'Tierra batida'), ('RESINA', 'Resina')], default='RESINA', max_length=10),
        ),
        migrations.AddField(
            model_name='turno',
            name='hora_fin_verano',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='hora_inicio_verano',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
