# Generated by Django 5.1.15 on 2026-08-07 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0007_pista_superficie_turno_hora_fin_verano_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenador',
            name='divisiones_habilitadas',
            field=models.ManyToManyField(blank=True, related_name='entrenadores', to='academy.division'),
        ),
        migrations.CreateModel(
            name='VacacionesEntrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacaciones', to='academy.entrenador')),
            ],
            options={
                'verbose_name': 'Vacaciones de entrenador',
                'verbose_name_plural': 'Vacaciones de entrenadores',
                'ordering': ['fecha_inicio'],
            },
        ),
    ]
