# Generated by Django 5.1.15 on 2026-08-07 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0008_entrenador_divisiones_habilitadas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsableJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.PositiveSmallIntegerField(default=1)),
                ('porcentaje_objetivo', models.PositiveSmallIntegerField(default=0, help_text='0-100. La suma por jugador no debería pasar de 100.')),
                ('activo', models.BooleanField(default=True)),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores_responsable', to='academy.entrenador')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsables', to='academy.jugador')),
            ],
            options={
                'verbose_name': 'Responsable de jugador',
                'verbose_name_plural': 'Responsables de jugador',
                'ordering': ['jugador', 'prioridad'],
                'unique_together': {('jugador', 'entrenador')},
            },
        ),
    ]
