# Generated by Django 5.1.15 on 2026-08-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0012_seed_escuelas'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('descripcion', models.TextField(blank=True)),
                ('responsable', models.CharField(blank=True, max_length=120)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_CURSO', 'En curso'), ('HECHA', 'Hecha')], default='PENDIENTE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tarea de mantenimiento',
                'verbose_name_plural': 'Tareas de mantenimiento',
                'ordering': ['estado', 'fecha_limite', '-created_at'],
            },
        ),
    ]
