# Generated by Django 5.1.15 on 2026-08-11 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0015_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='solo_escuela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_exclusivos', to='academy.escuela'),
        ),
    ]
