# Generated by Django 5.1.15 on 2026-08-11 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0017_seed_turno_junior_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciaSuperficie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superficie', models.CharField(choices=[('TIERRA', 'Tierra batida'), ('RESINA', 'Resina')], max_length=10)),
                ('fecha_desde', models.DateField(blank=True, null=True)),
                ('fecha_hasta', models.DateField(blank=True, null=True)),
                ('estricta', models.BooleanField(default=True, help_text='Si está marcada, el motor nunca lo pone en otra superficie.')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_superficie', to='academy.jugador')),
            ],
            options={
                'verbose_name': 'Preferencia de superficie',
                'verbose_name_plural': 'Preferencias de superficie',
                'ordering': ['jugador', '-fecha_desde'],
            },
        ),
    ]
