# Generated by Django 5.1.15 on 2026-08-11 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0018_preferenciasuperficie'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitado',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academy.division'),
        ),
        migrations.AddField(
            model_name='invitado',
            name='edad',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitado',
            name='jugar_con',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academy.jugador'),
        ),
        migrations.AddField(
            model_name='invitado',
            name='pareja_estricta',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='invitado',
            name='superficie_pref',
            field=models.CharField(blank=True, choices=[('TIERRA', 'Tierra batida'), ('RESINA', 'Resina')], max_length=10),
        ),
        migrations.CreateModel(
            name='PreferenciaPareja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('HARD', 'Obligatoria (misma pista)'), ('SOFT', 'Preferente (bonus)')], default='HARD', max_length=4)),
                ('activa', models.BooleanField(default=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parejas_pref', to='academy.jugador')),
                ('jugador_objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parejas_pref_objetivo', to='academy.jugador')),
            ],
            options={
                'verbose_name': 'Preferencia de pareja',
                'verbose_name_plural': 'Preferencias de pareja',
                'unique_together': {('jugador', 'jugador_objetivo')},
            },
        ),
    ]
