# Generated by Django 5.1.15 on 2026-08-12 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0020_repartir_porcentajes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='solo_escuela',
        ),
        migrations.AddField(
            model_name='escuela',
            name='solo_central',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='escuela',
            name='turno_unico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escuelas_exclusivas', to='academy.turno'),
        ),
    ]
