# Generated by Django 5.1.15 on 2026-08-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0025_feedback_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='estado',
            field=models.CharField(choices=[('NUEVO', 'Nuevo'), ('EN_PROGRESO', 'En progreso'), ('HECHO', 'Implementado'), ('AJENO', 'Ajeno a esta plataforma'), ('DESCARTADO', 'Descartado')], default='NUEVO', max_length=12),
        ),
    ]
