# Generated by Django 5.1.15 on 2026-08-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0026_alter_feedback_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='sesiones_dia_max',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Máximo de sesiones el mismo día. Vacío = valor por defecto.', null=True),
        ),
        migrations.AddField(
            model_name='jugador',
            name='sesiones_semana',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Sesiones/semana objetivo. Vacío = valor por defecto del motor.', null=True),
        ),
    ]
