# Generated by Django 5.1.15 on 2026-09-07 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0028_turnos_curso_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='turno_manana',
            field=models.ForeignKey(blank=True, help_text='Franja de mañana fija. Vacío = cualquiera.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jugadores_manana', to='academy.turno'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='turno_tarde',
            field=models.ForeignKey(blank=True, help_text='Franja de tarde fija. Vacío = cualquiera.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jugadores_tarde', to='academy.turno'),
        ),
        migrations.AddField(
            model_name='turno',
            name='activo',
            field=models.BooleanField(default=True, help_text='Si no, el motor no reparte en este turno.'),
        ),
    ]
