# Generated by Django 5.1.15 on 2026-09-07 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0030_seed_septiembre_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado')])),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horario', to='academy.jugador')),
                ('turno_manana', models.ForeignKey(blank=True, limit_choices_to={'activo': True, 'bloque': 'MANANA'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios_manana', to='academy.turno', verbose_name='Turno de mañana')),
                ('turno_tarde', models.ForeignKey(blank=True, limit_choices_to={'activo': True, 'bloque': 'TARDE'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios_tarde', to='academy.turno', verbose_name='Turno de tarde')),
            ],
            options={
                'verbose_name': 'Horario del jugador',
                'verbose_name_plural': 'Horario semanal',
                'ordering': ['jugador', 'dia'],
                'unique_together': {('jugador', 'dia')},
            },
        ),
    ]
