# Generated by Django 5.1.15 on 2026-09-07 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0031_horario_semanal_jugador'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioEntrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado')])),
                ('manana', models.BooleanField(default=True, verbose_name='Trabaja por la mañana')),
                ('tarde', models.BooleanField(default=True, verbose_name='Trabaja por la tarde')),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horario', to='academy.entrenador')),
            ],
            options={
                'verbose_name': 'Jornada del entrenador',
                'verbose_name_plural': 'Jornada semanal',
                'ordering': ['entrenador', 'dia'],
                'unique_together': {('entrenador', 'dia')},
            },
        ),
    ]
