# Generated by Django 5.1.15 on 2026-09-07 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0033_turnos_definitivos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariojugador',
            name='turno_manana',
            field=models.ForeignKey(blank=True, limit_choices_to={'activo': True, 'bloque': 'MANANA', 'codigo__in': ['M1', 'M2']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios_manana', to='academy.turno', verbose_name='Turno de mañana'),
        ),
        migrations.AlterField(
            model_name='horariojugador',
            name='turno_tarde',
            field=models.ForeignKey(blank=True, limit_choices_to={'activo': True, 'bloque': 'TARDE', 'codigo__in': ['T1', 'T2']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios_tarde', to='academy.turno', verbose_name='Turno de tarde'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='turno_manana',
            field=models.ForeignKey(blank=True, help_text='M1 (8:30) o M2 (10:30). Vacío = cualquiera.', limit_choices_to={'codigo__in': ['M1', 'M2']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jugadores_manana', to='academy.turno'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='turno_tarde',
            field=models.ForeignKey(blank=True, help_text='T1 (14:15) o T2 (15:30). Vacío = cualquiera.', limit_choices_to={'codigo__in': ['T1', 'T2']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jugadores_tarde', to='academy.turno'),
        ),
    ]
