# Generated by Django 5.1.15 on 2026-09-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0034_alter_horariojugador_turno_manana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='fecha_alta',
            field=models.DateField(blank=True, help_text='Desde qué día entra en los entrenamientos. Vacío = desde siempre.', null=True, verbose_name='Fecha de alta'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='fecha_baja',
            field=models.DateField(blank=True, help_text='Último día que entrena. Vacío = sigue en activo.', null=True, verbose_name='Fecha de baja'),
        ),
    ]
