# Generated by Django 5.1.15 on 2026-09-14 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0035_jugador_fecha_alta_jugador_fecha_baja'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenador',
            name='turno_manana',
            field=models.ForeignKey(blank=True, help_text='M1 (8:30) o M2 (10:30). Vacío = cualquiera.', limit_choices_to={'codigo__in': ['M1', 'M2']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrenadores_manana', to='academy.turno'),
        ),
        migrations.AddField(
            model_name='entrenador',
            name='turno_tarde',
            field=models.ForeignKey(blank=True, help_text='T1 (14:15) o T2 (15:30). Vacío = cualquiera.', limit_choices_to={'codigo__in': ['T1', 'T2']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrenadores_tarde', to='academy.turno'),
        ),
    ]
