# Generated by Django 5.1.15 on 2026-09-14 10:38

from django.db import migrations, models


def conserva_el_significado(apps, schema_editor):
    """Lo que ya estaba escrito quería decir lo mismo de antes.

    Hasta ahora, una fila con el turno a nulo significaba «ese día no entrena en
    ese bloque»: no había forma de decir «entrena, en la que salga». Así que las
    filas existentes se marcan en consecuencia y nadie cambia de horario por
    culpa de esta migración.
    """
    Horario = apps.get_model("academy", "HorarioJugador")
    Horario.objects.filter(turno_manana__isnull=True).update(entrena_manana=False)
    Horario.objects.filter(turno_tarde__isnull=True).update(entrena_tarde=False)


def deshacer(apps, schema_editor):
    """Al revés no hay nada que hacer: los campos se van con el rollback."""


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0036_entrenador_turno_manana_entrenador_turno_tarde'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariojugador',
            name='entrena_manana',
            field=models.BooleanField(default=True, help_text='Si no, ese día no entrena por la mañana. Con el turno vacío, entrena en la franja que mejor encaje.', verbose_name='Entrena por la mañana'),
        ),
        migrations.AddField(
            model_name='horariojugador',
            name='entrena_tarde',
            field=models.BooleanField(default=True, help_text='Si no, ese día no entrena por la tarde. Con el turno vacío, entrena en la franja que mejor encaje.', verbose_name='Entrena por la tarde'),
        ),
        migrations.RunPython(conserva_el_significado, deshacer),
    ]
