# Generated by Django 5.1.15 on 2026-09-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0037_horariojugador_entrena_manana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='pareja_division',
            field=models.CharField(blank=True, choices=[('ARRIBA', 'Hacia arriba (división mejor, D-1)'), ('ABAJO', 'Hacia abajo (división de debajo, D+1)')], help_text='Siempre dentro de ±1 división. Vacío = le da igual.', max_length=6, null=True, verbose_name='Se empareja preferentemente'),
        ),
    ]
