# Generated by Django 5.1.15 on 2026-09-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0038_jugador_pareja_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='tipo',
            field=models.CharField(choices=[('DURO', 'Duro · siempre con él'), ('BLANDO', 'Blando · cuando pueda')], default='DURO', help_text='Duro: siempre con él. Blando: primero su grupo, y con este jugador cuando no deje ninguna pista sin entrenador.', max_length=6),
        ),
        migrations.AddField(
            model_name='vacacionesentrenador',
            name='ambito',
            field=models.CharField(choices=[('DIA', 'Todo el día'), ('MANANA', 'Toda la mañana'), ('TARDE', 'Toda la tarde'), ('M1', 'Turno M1'), ('M2', 'Turno M2'), ('JP', 'Junior Program'), ('T1', 'Turno T1'), ('T2', 'Turno T2')], default='DIA', help_text='Todo el día, un bloque o una franja concreta.', max_length=10),
        ),
    ]
