# Generated by Django 5.1.15 on 2026-09-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0039_contrato_tipo_vacacionesentrenador_ambito'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='vecindad',
            field=models.CharField(choices=[('CLUB', 'La del club'), ('SOLO', 'Solo su división'), ('ARRIBA', 'Su división y la de encima (D−1)'), ('ABAJO', 'Su división y la de debajo (D+1)'), ('AMBAS', 'Su división y las dos vecinas (±1)')], default='CLUB', help_text='Regla dura. «La del club» usa la horquilla general; el resto la estrecha solo para este alumno.', max_length=6, verbose_name='Con qué divisiones entrena'),
        ),
    ]
