# Generated by Django 5.1.15 on 2026-09-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0040_vecindad_por_jugador'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='sexo',
            field=models.CharField(blank=True, choices=[('CHICO', 'Chico'), ('CHICA', 'Chica')], default='', help_text='Un chico no comparte pista con una chica de división más baja. Vacío = sin declarar, no se le aplica la regla.', max_length=5),
        ),
    ]
