# Generated by Django 5.1.15 on 2026-09-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0041_sexo_del_jugador'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenador',
            name='reserva',
            field=models.BooleanField(default=False, help_text='El motor no le asigna pistas; se le coloca a mano desde el cuadrante.', verbose_name='Solo a mano (banquillo)'),
        ),
    ]
