# Generated by Django 5.1.15 on 2026-09-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0042_entrenador_de_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenador',
            name='division_desde',
            field=models.PositiveSmallIntegerField(blank=True, help_text='La más alta de su grupo (la 1 es la mejor). Vacío = cualquiera.', null=True, verbose_name='Entrena desde la división'),
        ),
        migrations.AddField(
            model_name='entrenador',
            name='division_hasta',
            field=models.PositiveSmallIntegerField(blank=True, help_text='La más baja de su grupo. Vacío = cualquiera.', null=True, verbose_name='hasta la división'),
        ),
    ]
