# Generated by Django 5.1.15 on 2026-09-23 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0043_grupos_del_entrenador'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='sin_prioridad',
            field=models.BooleanField(default=False, help_text='Se coloca el último, solo en pistas ya abiertas por otros.', verbose_name='Sin prioridad'),
        ),
        migrations.CreateModel(
            name='PreferenciaEntrenadorFranja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DURO', 'Duro · siempre que entrene en esa franja'), ('BLANDO', 'Blando · cuando se pueda')], default='DURO', max_length=6)),
                ('activa', models.BooleanField(default=True)),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_franja', to='academy.entrenador')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_franja', to='academy.jugador')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_jugador', to='academy.turno')),
            ],
            options={
                'verbose_name': 'Entrenador por franja',
                'verbose_name_plural': 'Entrenadores por franja',
                'unique_together': {('jugador', 'turno', 'entrenador')},
            },
        ),
        migrations.CreateModel(
            name='VetoEntrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('nota', models.CharField(blank=True, max_length=200)),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vetado_por', to='academy.entrenador')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vetos_entrenador', to='academy.jugador')),
            ],
            options={
                'verbose_name': 'Veto de entrenador',
                'verbose_name_plural': 'Vetos de entrenador',
                'unique_together': {('jugador', 'entrenador')},
            },
        ),
    ]
