# Generated by Django 5.1.15 on 2026-09-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0044_jugador_sin_prioridad_preferenciaentrenadorfranja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenador',
            name='solo_manual',
            field=models.BooleanField(default=False, help_text='El motor nunca le asigna pistas; solo se le coloca a mano desde el cuadrante.', verbose_name='Nunca en automático'),
        ),
    ]
