# Generated by Django 5.1.15 on 2026-10-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0045_entrenador_solo_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviso',
            name='tipo',
            field=models.CharField(choices=[('MOVIMIENTO', 'Movimiento de escuela'), ('INVITADO', 'Invitado'), ('MANTENIMIENTO', 'Mantenimiento'), ('CORTE', 'Cambio tras el corte'), ('GENERACION', 'Generación del día'), ('GENERAL', 'General')], default='GENERAL', max_length=14),
        ),
    ]
