# Generated by Django 5.1.15 on 2026-10-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0046_avisos_corte'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='cogestores',
            field=models.ManyToManyField(blank=True, related_name='jugadores_cogestionados', to='academy.entrenador', verbose_name='Comparte la gestión con'),
        ),
    ]
