# Generated by Django 5.1.15 on 2026-06-19 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(help_text='Lunes de la semana', unique=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADO', 'Publicado')], default='BORRADOR', max_length=12)),
                ('generado_at', models.DateTimeField(blank=True, null=True)),
                ('publicado_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Semana',
                'verbose_name_plural': 'Semanas',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado')])),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('AUSENCIA_JUGADOR', 'Ausencia jugador'), ('CALENTAMIENTO', 'Calentamiento'), ('EN_TORNEO', 'En torneo'), ('CLIMATOLOGIA', 'Climatología'), ('AUSENCIA_COACH', 'Ausencia coach')], max_length=20)),
                ('subtipo', models.CharField(blank=True, choices=[('LESION', 'Lesión'), ('ENFERMEDAD', 'Baja por enfermedad'), ('ESTUDIOS', 'Estudios'), ('PRUEBA_MEDICA', 'Prueba médica'), ('MILONGA', 'Milonga')], max_length=20)),
                ('nota', models.CharField(blank=True, max_length=200)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.jugador')),
                ('turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academy.turno')),
                ('semana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='scheduling.semana')),
            ],
            options={
                'verbose_name': 'Disponibilidad',
                'verbose_name_plural': 'Disponibilidades',
                'unique_together': {('semana', 'jugador', 'dia', 'turno')},
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado')])),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('AUSENCIA_JUGADOR', 'Ausencia jugador'), ('CALENTAMIENTO', 'Calentamiento'), ('EN_TORNEO', 'En torneo'), ('CLIMATOLOGIA', 'Climatología'), ('AUSENCIA_COACH', 'Ausencia coach')], default='DISPONIBLE', max_length=20)),
                ('manual', models.BooleanField(default=False)),
                ('entrenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academy.entrenador')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.jugador')),
                ('pista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academy.pista')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academy.turno')),
                ('semana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='scheduling.semana')),
            ],
            options={
                'verbose_name': 'Asignación',
                'verbose_name_plural': 'Asignaciones',
                'ordering': ['dia', 'turno__orden', 'pista'],
                'unique_together': {('semana', 'dia', 'turno', 'jugador')},
            },
        ),
    ]
