# Generated by Django 5.1.15 on 2026-06-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionMotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_asignacion', models.PositiveIntegerField(default=1000, help_text='Prioridad de que todos jueguen (dominante).')),
                ('peso_satelite', models.PositiveIntegerField(default=5, help_text='Penalización por usar una pista satélite.')),
                ('peso_repeticion', models.PositiveIntegerField(default=10, help_text='Penalización por repetir pareja (rotación).')),
                ('max_dias_misma_pista', models.PositiveSmallIntegerField(default=2, help_text='Repeticiones a partir de las cuales se penaliza fuerte.')),
                ('aplicar_vecindad', models.BooleanField(default=True, help_text='Aplicar la regla de división N±1.')),
                ('time_limit_s', models.PositiveSmallIntegerField(default=10, help_text='Tiempo máx. del solver por turno (segundos).')),
            ],
            options={
                'verbose_name': 'Configuración del motor',
                'verbose_name_plural': 'Configuración del motor',
            },
        ),
    ]
