# Generated by Django 5.1.15 on 2026-06-30 15:43

from django.db import migrations, models


def fill_ambito(apps, schema_editor):
    """Mapea el turno antiguo al nuevo ámbito para no romper el unique."""
    Disponibilidad = apps.get_model('scheduling', 'Disponibilidad')
    Turno = apps.get_model('academy', 'Turno')
    codigo_by_id = dict(Turno.objects.values_list('id', 'codigo'))
    for d in Disponibilidad.objects.exclude(turno_id=None):
        d.ambito = codigo_by_id.get(d.turno_id, 'DIA')
        d.save(update_fields=['ambito'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_entrenador_foto_url'),
        ('scheduling', '0002_configuracionmotor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='disponibilidad',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='ambito',
            field=models.CharField(choices=[('DIA', 'Todo el día'), ('MANANA', 'Toda la mañana'), ('TARDE', 'Toda la tarde'), ('M1', 'Turno M1'), ('M2', 'Turno M2'), ('T1', 'Turno T1'), ('T2', 'Turno T2')], default='DIA', max_length=10),
        ),
        migrations.AlterField(
            model_name='disponibilidad',
            name='subtipo',
            field=models.CharField(blank=True, choices=[('LESION', 'Lesión'), ('ENFERMEDAD', 'Baja por enfermedad'), ('ESTUDIOS', 'Estudios'), ('PRUEBA_MEDICA', 'Prueba médica'), ('VACACIONES', 'Vacaciones'), ('MILONGA', 'Milonga')], max_length=20),
        ),
        migrations.RunPython(fill_ambito, noop),
        migrations.AlterUniqueTogether(
            name='disponibilidad',
            unique_together={('semana', 'jugador', 'dia', 'ambito')},
        ),
    ]
