# Generated by Django 5.1.15 on 2026-08-07 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0008_entrenador_divisiones_habilitadas_and_more'),
        ('scheduling', '0004_configuracionmotor_peso_central'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibilidadEntrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado')])),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('TORNEO', 'En torneo (parcial)'), ('AUSENTE', 'No disponible')], default='DISPONIBLE', max_length=12)),
                ('hora_desde', models.TimeField(blank=True, null=True)),
                ('hora_hasta', models.TimeField(blank=True, null=True)),
                ('nota', models.CharField(blank=True, max_length=200)),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='academy.entrenador')),
                ('semana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades_entrenador', to='scheduling.semana')),
            ],
            options={
                'verbose_name': 'Disponibilidad de entrenador',
                'verbose_name_plural': 'Disponibilidades de entrenador',
                'unique_together': {('semana', 'entrenador', 'dia')},
            },
        ),
    ]
