# Generated by Django 5.1.15 on 2026-08-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_disponibilidadentrenador'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionmotor',
            name='usar_satelites',
            field=models.BooleanField(default=True, help_text='Desbordar a los clubs satélite cuando el Resort se llena. En verano se desactiva: lo que no cabe queda en el banquillo.'),
        ),
    ]
