# Generated by Django 5.1.15 on 2026-08-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_configuracionmotor_usar_satelites'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionmotor',
            name='permitir_individuales',
            field=models.BooleanField(default=True, help_text='Permitir pistas de un solo jugador (clase particular) cuando no hay con quién emparejarlo.'),
        ),
        migrations.AddField(
            model_name='configuracionmotor',
            name='peso_carga_entrenador',
            field=models.PositiveIntegerField(default=4, help_text='Cuánto pesa equilibrar la carga entre entrenadores frente a respetar los % objetivo de cada jugador.'),
        ),
        migrations.AddField(
            model_name='configuracionmotor',
            name='peso_densidad',
            field=models.PositiveIntegerField(default=400, help_text='Penalización por cada jugador por encima de la densidad normal de la pista (2). Permite subir a 3-4 solo cuando hace falta para que alguien entrene.'),
        ),
        migrations.AddField(
            model_name='configuracionmotor',
            name='sesiones_dia_max_default',
            field=models.PositiveSmallIntegerField(default=2, help_text='Máximo de sesiones el mismo día por jugador.'),
        ),
        migrations.AddField(
            model_name='configuracionmotor',
            name='sesiones_semana_default',
            field=models.PositiveSmallIntegerField(default=4, help_text='Sesiones/semana que se intenta dar a cada jugador sin objetivo propio. Manda sobre el nivel: nadie repite hasta que todos han cubierto su cupo.'),
        ),
    ]
