# Generated by Django 5.1.15 on 2026-08-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_configuracionmotor_permitir_individuales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionmotor',
            name='peso_pista_abierta',
            field=models.PositiveIntegerField(default=500, help_text='Coste de abrir una pista. Hace que el motor agrupe de dos en dos en vez de repartir clases individuales.'),
        ),
    ]
