# Generated by Django 5.1.15 on 2026-09-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_configuracionmotor_peso_pista_abierta'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionmotor',
            name='sesiones_bloque_max',
            field=models.PositiveSmallIntegerField(default=1, help_text='Máximo de sesiones en el mismo bloque (mañana o tarde). En los cuadrantes reales, de 249 jugadores con doble sesión en un día, 248 la hacen mañana+tarde y solo 1 dos mañanas.'),
        ),
    ]
