# Generated by Django 5.1.15 on 2026-09-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0009_configuracionmotor_sesiones_bloque_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionmotor',
            name='vecindad_max',
            field=models.PositiveSmallIntegerField(default=1, help_text='Diferencia máxima de división dentro de una pista. A 1 (N±1) quedan fuera el 30% de las parejas que la dirección deportiva forma de verdad; a 2, solo el 9%.'),
        ),
        migrations.AlterField(
            model_name='configuracionmotor',
            name='aplicar_vecindad',
            field=models.BooleanField(default=True, help_text='Aplicar la regla de vecindad de divisiones.'),
        ),
    ]
