# Generated by Django 5.1.15 on 2026-09-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0010_configuracionmotor_vecindad_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionmotor',
            name='peso_pareja',
            field=models.PositiveIntegerField(default=5000, help_text='Bonus por juntar una pareja preferente. Va en la misma escala que peso_asignacion x prioridad: desempata entre compañeros igual de válidos sin llegar a dejar a nadie fuera.'),
        ),
    ]
