# Generated by Django 5.1.15 on 2026-09-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0011_configuracionmotor_peso_pareja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidad',
            name='ambito',
            field=models.CharField(choices=[('DIA', 'Todo el día'), ('MANANA', 'Toda la mañana'), ('TARDE', 'Toda la tarde'), ('M1', 'Turno M1 (8:30-10:00)'), ('M2', 'Turno M2 (10:30-12:30)'), ('JP', 'Junior Program (12:30-14:30)'), ('T1', 'Turno T1 (14:15-15:30)'), ('T2', 'Turno T2 (15:30-17:30)')], default='DIA', max_length=10),
        ),
    ]
