# Generated by Django 5.1.15 on 2026-09-07 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0034_alter_horariojugador_turno_manana_and_more'),
        ('scheduling', '0012_alter_disponibilidad_ambito'),
    ]

    operations = [
        migrations.CreateModel(
            name='AusenciaJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('ambito', models.CharField(choices=[('DIA', 'Todo el día'), ('MANANA', 'Toda la mañana'), ('TARDE', 'Toda la tarde'), ('M1', 'Turno M1 (8:30-10:00)'), ('M2', 'Turno M2 (10:30-12:30)'), ('JP', 'Junior Program (12:30-14:30)'), ('T1', 'Turno T1 (14:15-15:30)'), ('T2', 'Turno T2 (15:30-17:30)')], default='DIA', help_text='Todo el día, una parte de la jornada o una franja concreta.', max_length=10)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('AUSENCIA_JUGADOR', 'Ausencia jugador'), ('CALENTAMIENTO', 'Calentamiento'), ('EN_TORNEO', 'En torneo'), ('CLIMATOLOGIA', 'Climatología'), ('AUSENCIA_COACH', 'Ausencia coach')], default='AUSENCIA_JUGADOR', max_length=20)),
                ('subtipo', models.CharField(blank=True, choices=[('LESION', 'Lesión'), ('ENFERMEDAD', 'Baja por enfermedad'), ('ESTUDIOS', 'Estudios'), ('PRUEBA_MEDICA', 'Prueba médica'), ('VACACIONES', 'Vacaciones'), ('MILONGA', 'Milonga')], max_length=20)),
                ('nota', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('declarada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ausencias_declaradas', to='academy.entrenador')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ausencias', to='academy.jugador')),
            ],
            options={
                'verbose_name': 'Ausencia por fechas',
                'verbose_name_plural': 'Ausencias por fechas',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
