# Generated by Django 5.1.15 on 2026-09-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0013_ausencia_por_fechas'),
    ]

    operations = [
        migrations.AddField(
            model_name='ausenciajugador',
            name='hora_desde',
            field=models.TimeField(blank=True, help_text='Solo para ausencias de un día.', null=True),
        ),
        migrations.AddField(
            model_name='ausenciajugador',
            name='hora_hasta',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
