# Generated by Django 5.1.15 on 2026-09-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0014_ausencia_con_horas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('AUSENCIA_JUGADOR', 'Ausencia jugador'), ('CALENTAMIENTO', 'Calentamiento'), ('EN_TORNEO', 'En torneo'), ('CLIMATOLOGIA', 'Climatología'), ('AUSENCIA_COACH', 'Ausencia coach'), ('EXTRA', 'Viene además')], default='DISPONIBLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='ausenciajugador',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('AUSENCIA_JUGADOR', 'Ausencia jugador'), ('CALENTAMIENTO', 'Calentamiento'), ('EN_TORNEO', 'En torneo'), ('CLIMATOLOGIA', 'Climatología'), ('AUSENCIA_COACH', 'Ausencia coach'), ('EXTRA', 'Viene además')], default='AUSENCIA_JUGADOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='disponibilidad',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('AUSENCIA_JUGADOR', 'Ausencia jugador'), ('CALENTAMIENTO', 'Calentamiento'), ('EN_TORNEO', 'En torneo'), ('CLIMATOLOGIA', 'Climatología'), ('AUSENCIA_COACH', 'Ausencia coach'), ('EXTRA', 'Viene además')], max_length=20),
        ),
    ]
