# Generated by Django 5.1.15 on 2026-09-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0015_alter_asignacion_estado_alter_ausenciajugador_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionmotor',
            name='sesiones_semana_default',
        ),
        migrations.AddField(
            model_name='configuracionmotor',
            name='peso_equilibrio_franjas',
            field=models.PositiveIntegerField(default=200, help_text='Cuánto cuesta cada jugador de desequilibrio entre las franjas de un bloque (8:30 y 10:30; 14:15 y 15:30). Se reparten en proporción a los entrenadores de cada franja. Por debajo de lo que cuesta abrir una pista, para no partir parejas en individuales solo por cuadrar.'),
        ),
    ]
