# Generated by Django 5.1.15 on 2026-09-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0016_equilibrio_franjas_sin_cupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionmotor',
            name='peso_resina',
            field=models.PositiveIntegerField(default=300, help_text='Coste de abrir una pista de resina. La academia entrena en tierra: la resina solo se usa cuando ya no queda tierra o cuando el alumno la tiene declarada en su ficha.'),
        ),
    ]
