# Generated by Django 5.1.15 on 2026-09-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0017_peso_resina'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionmotor',
            name='peso_pista_division',
            field=models.PositiveIntegerField(default=50, help_text='Cuánto tira cada división hacia su pista: la 1 a la pista 1 y así. Es un desempate —ordena las pistas cuando hay sitio—, nunca deja a nadie fuera.'),
        ),
    ]
