# Generated by Django 5.1.15 on 2026-09-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0018_peso_pista_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionmotor',
            name='peso_division_entrenador',
            field=models.PositiveIntegerField(default=1000, help_text='Cuánto cuesta que un entrenador coja un grupo que no es el suyo, por cada división de distancia. Pesa más cuanto más arriba está el alumno: el grupo 1 es el más estricto. Nunca deja una pista sin entrenador.'),
        ),
    ]
