# Generated by Django 5.1.15 on 2026-09-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0019_grupos_del_entrenador'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionmotor',
            name='capacidad_manana',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Máximo de jugadores por pista (mañana)'),
        ),
        migrations.AddField(
            model_name='configuracionmotor',
            name='capacidad_tarde',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Máximo de jugadores por pista (tarde)'),
        ),
        migrations.AddField(
            model_name='configuracionmotor',
            name='estiron_division',
            field=models.PositiveSmallIntegerField(default=1, help_text='Solo para quien usa la horquilla del club; el alumno que tiene la suya declarada en la ficha no se estira nunca.', verbose_name='Divisiones que se pueden estirar'),
        ),
        migrations.AddField(
            model_name='configuracionmotor',
            name='estiron_edad',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Años de edad que se pueden estirar'),
        ),
        migrations.AddField(
            model_name='configuracionmotor',
            name='peso_exceso_pistas',
            field=models.PositiveIntegerField(default=600, help_text='Por la mañana es una preferencia (no puede haber tres por pista, así que a veces no salen las cuentas). Por la tarde es un tope y no se usa.', verbose_name='Coste de abrir más pistas que entrenadores'),
        ),
        migrations.AddField(
            model_name='configuracionmotor',
            name='peso_individual',
            field=models.PositiveIntegerField(default=1200, help_text='Antes una pareja y una pista vacía que dos individuales. Dos individuales tienen que costar más que estirar la vecindad, o el motor nunca juntará a los que le sobran.', verbose_name='Coste de una pista de un solo jugador'),
        ),
        migrations.AddField(
            model_name='configuracionmotor',
            name='peso_relajar_vecindad',
            field=models.PositiveIntegerField(default=800, help_text='Lo que cuesta juntar a dos que se pasan por una división o un año. Solo se paga cuando evita dejarlos solos.', verbose_name='Coste de estirar división o edad'),
        ),
        migrations.AddField(
            model_name='configuracionmotor',
            name='peso_segunda_franja_tarde',
            field=models.PositiveIntegerField(default=2500, help_text='Por la tarde todos a T1 mientras quepan, aunque haya que hacer pistas de tres. T2 solo cuando T1 está lleno.', verbose_name='Coste de mandar a alguien a T2'),
        ),
    ]
