# Generated by Django 5.1.15 on 2026-09-23 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0020_configuracionmotor_capacidad_manana_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CambioSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=120)),
                ('foto', models.JSONField(default=list)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('semana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios', to='scheduling.semana')),
            ],
            options={
                'verbose_name': 'Cambio a mano',
                'verbose_name_plural': 'Cambios a mano',
                'ordering': ['-creado_at', '-id'],
            },
        ),
    ]
