# Generated by Django 5.1.15 on 2026-09-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0021_cambiosemana'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionmotor',
            name='peso_densidad_tarde',
            field=models.PositiveIntegerField(default=200, help_text='Por la tarde vale más una pista de tres que dejar a alguien fuera, así que apretar cuesta mucho menos que por la mañana. Tiene que estar por debajo de peso_asignacion.', verbose_name='Coste del tercer jugador en una pista (tarde)'),
        ),
    ]
