# Generated by Django 5.1.15 on 2026-09-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0022_configuracionmotor_peso_densidad_tarde'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionmotor',
            name='nivel_protegido',
            field=models.PositiveSmallIntegerField(default=2, help_text='Sus pistas se cubren las primeras y, si no llega el reparto, se saca a un entrenador del banquillo. 0 lo desactiva.', verbose_name='Divisiones que nunca se quedan sin entrenador'),
        ),
    ]
