# Generated by Django 5.1.15 on 2026-09-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0023_configuracionmotor_nivel_protegido'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionmotor',
            name='peso_orden_pista',
            field=models.PositiveIntegerField(default=60, help_text='Cierra los huecos: antes de abrir la 5 se abre la 4.', verbose_name='Coste de abrir una pista lejos de la primera'),
        ),
        migrations.AddField(
            model_name='configuracionmotor',
            name='tolerancia_division',
            field=models.PositiveSmallIntegerField(default=2, help_text='Límite, no coste: Dani Gimeno lleva el grupo 1-2 y con 2 llega hasta la 4, pero no acaba con un D7. Solo cede en la pista que, con el límite puesto, no admitiría a nadie.', verbose_name='Divisiones que un entrenador se sale de su grupo'),
        ),
        migrations.AlterField(
            model_name='configuracionmotor',
            name='peso_densidad_tarde',
            field=models.PositiveIntegerField(default=1000, help_text='Tiene que estar POR ENCIMA de peso_pista_abierta, para que mientras quede un entrenador libre se abra otra pista en vez de meter a un tercero; y por debajo de peso_pista_abierta + peso_individual, para que con un número impar salga el trío y no la clase individual.', verbose_name='Coste del tercer jugador en una pista (tarde)'),
        ),
    ]
