# Generated by Django 5.1.15 on 2026-09-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0024_configuracionmotor_peso_orden_pista_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionmotor',
            name='nivel_solo_tierra',
            field=models.PositiveSmallIntegerField(default=2, help_text='Las divisiones hasta esta no entrenan en resina salvo que se les declare la superficie en la ficha. 0 lo desactiva.', verbose_name='Divisiones que no pisan resina'),
        ),
    ]
