# Generated by Django 5.1.15 on 2026-09-29 10:37

from django.db import migrations, models


def tres_dias(apps, schema_editor):
    # El default solo vale para filas nuevas: la configuración que ya existe
    # (prod y copias) se pone a mano al tope que ha pedido el club.
    apps.get_model("scheduling", "ConfiguracionMotor").objects.update(max_dias_misma_pista=3)


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0025_configuracionmotor_nivel_solo_tierra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionmotor',
            name='estiron_division',
            field=models.PositiveSmallIntegerField(default=1, help_text='Solo por la tarde, y solo para quien usa la horquilla del club; el alumno que tiene la suya declarada en la ficha no se estira nunca.', verbose_name='Divisiones que se pueden estirar'),
        ),
        migrations.AlterField(
            model_name='configuracionmotor',
            name='max_dias_misma_pista',
            field=models.PositiveSmallIntegerField(default=3, help_text='Regla dura: dos alumnos no comparten pista más de estos días en la semana, aunque tengan la pareja declarada. Mañana y tarde del mismo día cuentan como uno. 0 = sin tope.', verbose_name='Máx. días juntos a la semana'),
        ),
        migrations.RunPython(tres_dias, migrations.RunPython.noop),
    ]
