# Generated by Django 5.1.15 on 2026-10-02 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0045_entrenador_solo_manual'),
        ('scheduling', '0026_tope_dias_pareja'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuitadoAMano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.PositiveSmallIntegerField()),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.jugador')),
                ('semana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quitados', to='scheduling.semana')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.turno')),
            ],
            options={
                'verbose_name': 'Quitado a mano',
                'verbose_name_plural': 'Quitados a mano',
                'unique_together': {('semana', 'dia', 'turno', 'jugador')},
            },
        ),
    ]
