# Generated by Django 5.1.15 on 2026-10-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0027_quitado_a_mano'),
    ]

    operations = [
        migrations.AddField(
            model_name='ausenciajugador',
            name='tardia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='tardia',
            field=models.BooleanField(default=False),
        ),
    ]
