# Generated by Django 5.1.15 on 2026-10-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0028_falta_tardia'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneracionProgramada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('iniciada_at', models.DateTimeField(auto_now_add=True)),
                ('terminada_at', models.DateTimeField(blank=True, null=True)),
                ('ok', models.BooleanField(default=False)),
                ('detalle', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Generación programada',
                'verbose_name_plural': 'Generaciones programadas',
                'ordering': ['-fecha'],
            },
        ),
    ]
