# Generated by Django 5.1.15 on 2026-08-11 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Administrador'), ('COACH', 'Coach'), ('ENTRENADOR', 'Entrenador')], default='ENTRENADOR', max_length=20),
        ),
    ]
